version: "3"
services:
  db:
    image: mysql:8.0.22
    container_name: wabigram
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/wabi/datadir/mysql/wabigram
